### ISSUE TITLE
Static methods don't display in commands list.

### ISSUE THREAD

**Issue by AwixStudio** [Huntrox/CommandConsole#1]
I have this static method in static class:
`[ConsoleCommand]
  public static void Cheat_ForceSpawn()
  {
      TogglePhysicsSystem(true);
      EnableSpawners();
  }     
`

but can't use it in command console.

It looks like CommandsHandles doesn't assign it to MethodCommands.

I looked into CommandsHandler code and foud this:
```     
private static void GetStaticClass()
{
    var assemblies = AppDomain.CurrentDomain.GetAssemblies();
    foreach (var assembly in assemblies)
    {
        var types = assembly.GetTypes();
        foreach (var type in Assembly.GetExecutingAssembly().GetTypes())
        (...)
```

After replacing `foreach (var type in Assembly.GetExecutingAssembly().GetTypes())` with `foreach (var type in types)` everything works fine

**Comment by Huntrox** [comment]
I think I actually forgot to change that I can see types where unused 
anyway thanks for the issue 

pushed changes c623f0da
